spring.application.name=zero

spring.datasource.url=jdbc:postgresql://localhost:5432/teampro
spring.datasource.username=postgres
spring.datasource.password=Nursultan2010_
spring.datasource.driver-class-name=org.postgresql.Driver
FRONTEND_URL=http://localhost:3000

spring.jpa.hibernate.ddl-auto=update